### ISSUE TITLE
select function return 0 result

### ISSUE THREAD

**Issue by syahnur197** [rorystandley/mysqli-crud-php-oop#12]
I want to select all from a table, but it returns 0 results, even though I have data in my table

**Comment by syahnur197** [comment]
I'm using the latest XAMPP, for some reason insert() and select() do not work as it used to be please help. The insert() didn't add anything to the table, and select() did not return anything. The database connection works fine. so connect() works as intended

**Comment by rorystandley** [comment]
I stupidly accepted a PR without testing! I've reverted the merge back and this should work again

**Comment by syahnur197** [comment]
wow thank you for the fast response! you save my day!

**Comment by rorystandley** [comment]
No problem!
