### ISSUE TITLE
Is there a way to do a query using UTF8?

### ISSUE THREAD

**Issue by decao** [rorystandley/MySQLi-CRUD-PHP-OOP#3]
Hi is there a way to do a mysql query using UTF8?

I tried to use set_chartset http://php.net/manual/pt_BR/mysqli.set-charset.php

but i got an error:

Fatal error: Call to undefined method Database::set_chartset()

**Comment by jbonnett92** [comment]
Haven't tested the code but have you tried adding this to the class this
```
public function set_chartset($set) {
    $this->myconn->set_chartset($set);
}
```
then call it
```
Database::set_chartset("UTF8");
```
