### ISSUE TITLE
Hi

### ISSUE THREAD

**Issue by alleory** [rorystandley/MySQLi-CRUD-PHP-OOP#5]
include ('class/crud.php');
$db = new Database();
$db->connect();
$db->select('news', "LIMIT 1"); It doesn't work
$res = $db->getResult();

it says Warning: Illegal string offset 'title' in C:\xampp\htdocs\OOP\index.php on line 78
Y 

How can i use LIMIT 1????

**Comment by alleory** [comment]
Can you show me some example how you use the LIMIT query???

**Comment by rorystandley** [comment]
I'm working from memory, I think it should be "name", null, "1=1 limit 1"
Not perfect but it should work
ThanksRory

**Comment by alleory** [comment]
can you show me example on this $db->select('news', "LIMIT 1");??

**Comment by alleory** [comment]
I've tried like this $db->select('news'null,"1=1 LIMIT 1"); but it does not work; so how can i use your method to output only one news on my page???

**Comment by rorystandley** [comment]
You'll have to wait until I am at my computer I am currently not






On Sun, Aug 23, 2015 at 10:00 AM -0700, "alleory" <notifications@github.com> wrote:












I've tried like this $db->select('news'null,"1=1 LIMIT 1"); but it does not work; so how can i use your method to output only one news on my page???

**Comment by alleory** [comment]
Ok i am waiting of you

**Comment by alleory** [comment]
??

**Comment by rorystandley** [comment]
No need to be rude...
If you look at in the class, you will find this -

public function select($table, $rows = '*', $join = null, $where = null, $order = null, $limit = null)

So you can see that limit is the last argument of 5...
