### ISSUE TITLE
Problems with using DB names with special character in it

### ISSUE THREAD

**Issue by royvandongen** [rorystandley/mysqli-crud-php-oop#6]
Hi,

I tried using the $db->select on my database test-db. However this failed, i have changed this rule : 
$tablesInDb = $this->myconn->query('SHOW TABLES FROM '.$this->db_name.' LIKE "'.$table.'"');

to 

$tablesInDb = $this->myconn->query('SHOW TABLES FROM `'.$this->db_name.'` LIKE "'.$table.'"');

please note the ` marks around the DB name.

Now everything works even with "special" characters.

**Comment by rorystandley** [comment]
Open a pull request and we can get it fixed!

**Comment by Miepermans** [comment]
I must honestly say, i have no idea how that works. i'm sorry, i'm no pro-user whatsoever :(

**Comment by ParagonJenko** [comment]
Done the pull request :)
